version: "3.9"

services:
  streamlit-app:
    build: .
    container_name: voice-ai-streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

  fastapi-app:
    build: .
    container_name: voice-ai-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn api:app --host 0.0.0.0 --port 8000
